[[heading]]
# NEA cover page
level = 1
greedy = true
font.name = "Times-Bold"
font.size = 12.0
# font.size_tolerance = 1e-5
# font.color = 0x000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 264.4620056152344
# bbox.top = 113.74666595458984
# bbox.right = 347.53759765625
# bbox.bottom = 125.74666595458984
# bbox.tolerance = 1e-5

[[heading]]
# 1.1. The current problem
level = 2
greedy = true
font.name = "Times-Bold"
font.size = 10.0
# font.size_tolerance = 1e-5
# font.color = 0x000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 110.99996948242188
# bbox.top = 253.2888946533203
# bbox.right = 220.6298828125
# bbox.bottom = 263.28887939453125
# bbox.tolerance = 1e-5

