CC=cc
CFLAGS=-O3

SRC = zpy.c comp.c tokenizer.c fileread.c util.c appendsnprintf.c
OBJ = ${SRC:.c=.o}

all: zpy 

.c.o:
	${CC} -c ${CFLAGS} $<
zpy: ${OBJ}
	${CC} -o $@ ${OBJ}
        cd stdlib && make
install: all 
	cp zpy /usr/local/bin/zpy
	cd stdlib && make install
	cd zpypkg && make install
clean:
	rm -rf zpy*.o
	cd stdlib && make clean
	cd examples && make clean
uninstall: 
	rm /usr/local/bin/zpy

.PHONY: all clean install uninstall
